checksumBehavior: ignore

nmHoistingLimits: workspaces

nodeLinker: node-modules

packageExtensions:
  "@tanstack/react-query@*":
    peerDependencies:
      react: "*"
  expo-router@*:
    peerDependencies:
      react: "*"
  nativewind@*:
    peerDependencies:
      react: "*"
